#!/bin/bash

echo "Enter initial for user1"; read user1;
echo "Enter initial for user2"; read user2;
echo "Enter commit message"; read commit;
echo "Enter git username/repo for user1"; read link1;
echo "Enter git username/repo for user2"; read link2;

git init; git pair $user1 $user2;
git add .; git pair-commit -m "$commit";
git remote add $user1 https://github.com/$link1;
git remote add $user2 https://github.com/$link2;

git push $user1 master; git push $user2 master;

echo "Meow~";
